name: Test

on: [push]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-ubuntu-latest-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-ubuntu-latest-${{ hashFiles('.ruby-version') }}-
    
    - name: Install build dependencies
      run: |
        gem install bundler:2.1.4

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle config set with 'test'
        bundle install --jobs 4 --retry 3

    - name: Run tests
      run: |
        rake test

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.5.7
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: rake test
        coverageLocations:
          "${{github.workspace}}/coverage/.resultset.json"
